### ISSUE TITLE
Link to respective sections from "14. Next steps"

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#101]
The overview list in "14. Next steps" could use links to appropriate sections (either in the UG or the E2E doc).

**Comment by mishaone** [comment]
Added non-inline links and merged: https://github.com/fabric8io/fabric8-online-docs/pull/112

I wanted to add inline links but that makes the phrasing very awkward so that the phrase and the link it points to need to be sufficiently clear. This is a bit clunkier, but more clear, I think. Leaving this open for @rkratky to confirm this is sufficient to close the issue.

**Comment by rkratky** [comment]
@mishaone, looks good, but I added one comment to the PR. Closing this.

**Comment by rkratky** [comment]
@mishaone, looks good, but I added one comment to the PR. Closing this.
