### ISSUE TITLE
Slight improvement to splash page

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#162]
First off, it's great to see we finally have our docs on docs.os.io. This was a passing thought I had about making the splash page look a bit nicer today.

Currently, the links to the two docs look like this:
![links](https://user-images.githubusercontent.com/926572/34928991-ec341c32-fa0c-11e7-9993-e74eea35a04d.png)

The default title link is HTML and PDF is separately listed in brackets. I think we can make this look a bit nicer if we have the name of the doc (no link) and then two linked options for HTML and PDF, and then a small blurb about the doc. Something like this, maybe:

OpenShift.io Getting Started Guide [ HTML | PDF ]
New to OpenShift.io? Use this document to explore OpenShift.io and start creating applications!     //trying to invoke whimsy and excitement here

OpenShift.io User Guide [ HTML | PDF ]
After mastering the basics, use this document for a comprehensive look at OpenShift.io and all its features.

@Preeticp @rkratky WDYT? I feel the splash page feels a bit empty at the moment. We should probably also remove the bullet points.

**Comment by rkratky** [comment]
Hi @mishaone, we already have an issue open about this: https://github.com/fabric8io/fabric8-online-docs/issues/40. I have asked the UX team to help with this, and they're working on it at https://github.com/fabric8-ui/fabric8-ux/issues/703

As for your suggestions, I agree with adding a description (perhaps it could be the abstract we already have in the guides). I do want to keep the link to the HTML version as the title of the guide because of SEO though.

The bullets are only there because of my lack of imagination. The page is currently generated automatically from a static adoc template (`docs/index-templ.adoc`) -- i.e. the build script parses the repo available docs and generates the landing page accordingly. I would like to preserve this bit of automation, but I'm happy to reformat the page (before we get the page from the UX team).

**Comment by mishaone** [comment]
Sounds good, Robert. I'm happy to keep this open or close it. These were just some thoughts I had looking at the splash page now that it's finally externally available.

**Comment by rkratky** [comment]
Ok, thanks. Closing this. Please, continue commenting in #40.
