### ISSUE TITLE
Update screenshots, text for a new login screen

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#185]
Catherine: I just wanted to point out that this release will include a new log in page that looks different that the current OSIO log in page.  We'll probably need to check out screen shots in documentation and make sure we update them. Here's where you can see the new OSIO log in Staged: https://developers.stage.redhat.com/auth/realms/rhd/protocol/openid-connect/auth?scope=openid&state=RLjoxdLnItGvUDME83uE9AJKCzcydG4cxiw1Yg7lBRI.fabric8-online-platform&response_type=code&client_id=osio&redirect_uri=https%3A%2F%2Fsso.openshift.io%2Fauth%2Frealms%2Ffabric8%2Fbroker%2Frhd%2Fendpoint

**Comment by rkratky** [comment]
@mishaone, I see this has now been deployed to prod. Could you please take it up now?

**Comment by mishaone** [comment]
Ack, will do tomorrow

**Comment by mishaone** [comment]
So it looks like the screenshots aren't very relevant to the UG (no screenshots for this part) and the GS doc doesn't really have anything on a generic login since it starts with the first time login (which includes adding your GH and OSO accounts to the OSIO account, etc. but not a generic log in). Should there be one? I'm reluctant to add screenshots to the UG since this is a fairly basic thing and probably doesn't need them, or to the GS guide because the workflow there is a first time log in. Thoughts?

**Comment by rkratky** [comment]
Even better. No need to add a screenshot for such a trivial thing. Closing.
