### ISSUE TITLE
Create a CONTRIBUTING.adoc for this repository

### ISSUE THREAD

**Issue by Preeticp** [fabric8io/fabric8-online-docs#189]
We need a contributing guidelines doc for this repository, which would also house the conventions followed in the docs. I will start  a PR for the same and get this rolling.
@rkratky, @mishaone we are following many conventions based on our discussions in the comments of Issues/PRs, it would probably be a good idea to list all of them here.

**Comment by mishaone** [comment]
I'm working on this, but would adding information to the README.md work better than a separate adoc file that would need to be hosted somewhere?

**Comment by Preeticp** [comment]
My 2 cents:
A separate Contributing makes sense to me, in fact I would suggest certain sections from the Readme could probably go to the contributing.
Readme should probably me more generic, explaining the contents of this repo, objective, link to the contributing doc etc.

**Comment by mishaone** [comment]
The current readme seems reasonably useful to me as it is. I'd just add a contributing section to it before the building and testing stuff, since that would be the order. I'd also suggest that contributing should be up front and automatically displaying in the README to encourage people to contribute directly rather than have a separate Contributing doc, especially since that would also include some quick information about the repo structure. So to me, this feels like killing two birds with one stone rather than displaying generic About the repo info in the README and having a separate file you need to click to start contributing.

I'm working on this in a separate file for now and I guess we'll wait for @rkratky to weigh in with the deciding vote and go with that since we're each in favor of a slightly different option. :)

**Comment by Preeticp** [comment]
@mishaone I am not married to either views, so if you feel a single doc is the way to go, please go ahead. Let's just get the information in, we can always restructure later. Main point, on which I am sure we all agree, is that we need to follow these conventions. :)

**Comment by mishaone** [comment]
Absolutely. I've also asked the docs convention project to have an externally available link to their convention recommendations, which should hopefully help us shave down the individual guidance we need to add to this, but that's not around at the moment.

**Comment by rkratky** [comment]
The reason for a separate CONTRIBUTING file is that Github expects it and automatically offers it to potential contributors for reading. See https://github.com/blog/1184-contributing-guidelines

_We've tried making this easy for everyone. As a maintainer, all you have to do is add a CONTRIBUTING file (or CONTRIBUTING.md if you're using Markdown) to the root of your repository. Then we will add a link to your file when a contributor creates an Issue or opens a Pull Request._

**Comment by mishaone** [comment]
Ah, I didn't know that. It makes sense to have a separate doc if that's the mechanism. Thanks for clearing it up, Robert! I'll shift around my changes to a new doc and create a PR.

**Comment by mishaone** [comment]
PR1 (https://github.com/fabric8io/fabric8-online-docs/pull/193) created today and tagged Robert and Preeti for their input on how it's going so far.

**Comment by mishaone** [comment]
PR2: https://github.com/fabric8io/fabric8-online-docs/pull/197

**Comment by mishaone** [comment]
PR3 (markdown conventions): https://github.com/fabric8io/fabric8-online-docs/pull/200

**Comment by mishaone** [comment]
PR4: https://github.com/fabric8io/fabric8-online-docs/pull/201

**Comment by mishaone** [comment]
That should be the changes to README and CONTRIBUTING taken care of. Closing issue.
