### ISSUE TITLE
4.12. Configuring your Che workspace shows wrong run command setup

### ISSUE THREAD

**Issue by brizrobbo** [fabric8io/fabric8-online-docs#204]
_[Not sure if this issue should be in Documentation or Product]_

In [Section 4.12. Configuring your Che workspace](https://docs.openshift.io/getting-started-guide.html#configuring_your_che_workspace-hello-world) of the [OpenShift.io Getting Started Guide](https://docs.openshift.io/getting-started-guide.html#creating_che_workspace-hello-world), point 2 (d) shows:

d. Click the *run* option from the Run button (tri-run-image) ....

When I ran it, it did not give me any options to 'run' as shown in the tri-run-image. The sub option for me when I hit run was "Create run command". I had to manually go an create my own run command to get it to work.

This could have been because my Che environment was not setup correctly, but I did follow the previous steps in 2. a) - c).

**Comment by mishaone** [comment]
Admittedly, I've never seen this option before. @joshuawilson can you tag someone who would know if this is a valid option and why it would appear?

**Comment by Preeticp** [comment]
Hi @mishaone I tried following this with the Che folks on Jan 22, unfortunately received no response, and it fell of my plate with other things taking priority. I will find a link to the archived mail, meanwhile here is the mail copied over for further reference:

Hi Mario, Gorkem,

I am part of the OSIO docs team and have been updating the Getting Started guide for OSIO [1] (which is based on Todd's Getting started PDF). 

I see some differences in the Che Workspace behavior from what was documented earlier, and have the following questions with respect to it.

Context: I have been importing the Vertx Eventbus as per section 10.3 and have imported and reset my environment a couple of times.

Expected behavior and observed deviations in the current Che workspace:

i. As per the guide, Section 10.4, step 2 [2]:

In the Create Tab, Workspaces section, I should see 'Create workspace'. I saw this the first time I imported the code. 
However when I reset my environment (from my profile), create a fresh space, and then import the Eventbus code, I see 'Select a workspace' dropdown with vertx-eventbus-quj7k option.
Inline image 4

Questions:
Is this expected behavior? That is, I do not need to create a workspace? It seems like a workspace was already created for me or continued to carry forward from my previous attempt, which I need to select and open. 
So does a reset environment simply delete my space and has no effect on the Che workspace? 
Is there any other way I can delete a Che workspace and start again fresh?

ii. As per Section 10.5, step 2d [1]:
I should see Run on hovering over the Run button. However 2 days back I saw:
Inline image 2

          and then yesterday this:
Inline image 3  

iii. Section 10.5, step 3: 
Clicking on the drop-down gives me the 'newCustom' option, which creates a 'newCustom' tab in the Processes pane, this deviates from Step 3 and the workshop/end to end scenario. It also prevents me from doing any of the next steps in the section.

Questions: 
Is this a new feature? If so what does it enable an user to do?
In the current UX how does a user download the required dependencies, compile the application, and start the verticle?
How can he/she access the Preview URL?
Request answers for the above questions so that I am able to update the documentation accordingly.

[1] https://docs.openshift.io/getting-started-guide.html#configuring_your_che_workspace-importing-existing-project
[2] https://docs.openshift.io/getting-started-guide.html#creating_che_workspace-importing-existing-project
Hi Mario, Gorkem,

I am part of the OSIO docs team and have been updating the Getting Started guide for OSIO [1] (which is based on Todd's Getting started PDF). 

I see some differences in the Che Workspace behavior from what was documented earlier, and have the following questions with respect to it.

Context: I have been importing the Vertx Eventbus as per section 10.3 and have imported and reset my environment a couple of times.

Expected behavior and observed deviations in the current Che workspace:

i. As per the guide, Section 10.4, step 2 [2]:

In the Create Tab, Workspaces section, I should see 'Create workspace'. I saw this the first time I imported the code. 
However when I reset my environment (from my profile), create a fresh space, and then import the Eventbus code, I see 'Select a workspace' dropdown with vertx-eventbus-quj7k option.
Inline image 4

Questions:
Is this expected behavior? That is, I do not need to create a workspace? It seems like a workspace was already created for me or continued to carry forward from my previous attempt, which I need to select and open. 
So does a reset environment simply delete my space and has no effect on the Che workspace? 
Is there any other way I can delete a Che workspace and start again fresh?

ii. As per Section 10.5, step 2d [1]:
I should see Run on hovering over the Run button. However 2 days back I saw:
Inline image 2

          and then yesterday this:
Inline image 3  

iii. Section 10.5, step 3: 
Clicking on the drop-down gives me the 'newCustom' option, which creates a 'newCustom' tab in the Processes pane, this deviates from Step 3 and the workshop/end to end scenario. It also prevents me from doing any of the next steps in the section.

Questions: 
Is this a new feature? If so what does it enable an user to do?
In the current UX how does a user download the required dependencies, compile the application, and start the verticle?
How can he/she access the Preview URL?
Request answers for the above questions so that I am able to update the documentation accordingly.

[1] https://docs.openshift.io/getting-started-guide.html#configuring_your_che_workspace-importing-existing-project
[2] https://docs.openshift.io/getting-started-guide.html#creating_che_workspace-importing-existing-project

Thank you,
Regards,
Preeti

**Comment by Preeticp** [comment]
I see the images are not rendering properly I will try to add them here.

**Comment by mishaone** [comment]
@brizrobbo and @Preeticp - this sounds like an issue in OSIO rather than the docs. Can we copy over the details as reported by both of you to a new issue in their repo so that it can get attention from the che team or be evaluated as a known issue that needs documentation?

**Comment by joshuawilson** [comment]
I agree, this should be written up on https://github.com/openshiftio/openshift.io/issues. 
Ping @gorkem @l0rd

**Comment by brizrobbo** [comment]
I have now migrated over to https://github.com/openshiftio/openshift.io/issues/2611.

Will close this issue.
