### ISSUE TITLE
Validate new CSS

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#35]
@mishaone, @Preeticp, at your convenience, please, check the UG (at https://docs.prod-preview.openshift.io/) for any formatting or rendering problems that may have been caused by the application of the new styling. For reference, this is the LOSIO docs from which the styling was taken: https://appdev.openshift.io/docs/minishift-installation.html

Two known issues I'm working on:

- logos in the header and footer of the page are not showing
- doc timestamp isn't displayed

**Comment by Preeticp** [comment]
Hi Robert,
On first look, here are a few of my observations:
**UI fields** 
Losio: Italics.
We: We have btn[field] for buttons, bold for other UI fileds and back ticks (9.2) too in some places, which are now rendered in red, with the new css. 
Do we want to distinguish the fields into buttons and others? A simple bold/italics for all UI elements irrespective of it being a button, tab, subtab, seems enough. wdyt?

**Kebab Menu**
Losio: Three-dot menu
We: Screen capture wrapped in parenthesis. IMO screencapture without parenthesis looks good. Do we need these square and round parenthesis around button names and menu names?

Commands:
Losio: In Red do we want to go the same way? 
We: Not used yet I guess, we might end up using them rarely, since ours is more UI based and less of commands.

**Comment by mishaone** [comment]
+1 for differentiating between UI elements. btn:[] for clickable buttons, and different appearances for labels (``) vs field names (**). I would opt on the side of variety in this case because different styles help break the monotony of what is mostly a wall of text and set apart what specific things to look for in a UI and what they are.

**Comment by rkratky** [comment]
Thanks for the comments. I will talk about the colors and other stuff with the RHOAR people, so that we coordinate the changes, and the styles don't diverge.

As for styling of particular elements, we need to start looking at https://redhat-documentation.github.io/asciidoc-markup-conventions/ for guidance to unify the look across RH docs. Since the style originated with OSIO UX people, I'm going to talk to them about how they would feel about updating/modifying it.

**Comment by rkratky** [comment]
Served its purpose. Closing.
