### ISSUE TITLE
Planning your development work should probably be moved

### ISSUE THREAD

**Issue by mishaone** [fabric8io/fabric8-online-docs#388]
I was reviewing the GSG and noticed the planning section is at an abrupt break in the document. The module before it is creating a new space. The one after it continues from the automatic Create an Application screen that appears when you finish making a space, so the abrupt detour to planning doesn't work very well as a user following these instructions.

cc: @Preeticp do you want to work this one out since I assume you decided on the placement here originally?

**Comment by Preeticp** [comment]
We [added this module]( https://github.com/fabric8io/fabric8-online-docs/pull/300) post extensive reviews by you and @rkratky . I really would not label this a bug in that context, seems more like an enhancement.
Can you please elaborate on what exactly do you think we need to do in this case. Having the Planning module at the start creates a connected narrative and provides a context for all the actions we ask the users to do post the launcher wizard actions, otherwise they seem like random disparate acts to first time users.
I agree, it is abrupt in the sense that we need to close the application launcher which comes up immediately after you create a space. But if you consider a workflow of creating a space, planning your devp workflow, and then launching an app as part of your devp work, it seems logical. Planning generally precedes execution. 
Also creating a Space and creating your codebase are 2 separate actions, with separate modals, planning does not require you to launch an application.
To ensure the user does not lose the flow of creating the application using the launcher a sentence saying 'If you closed the wizard earlier, click Create an Application in your space dashboard to see the wizard again.' has been added in the introductory paragraph of the [module immediately following](https://docs.openshift.io/getting-started-guide.html#creating_new_project-hello-world) the Planner module. 
Let me know if you have any other suggestions on this.
Again, we also have the Board view and Scrum template coming in which might require a total overhaul of this entire module in the coming train. I would suggest we wait for that and then take a call on this. Wdyt?

**Comment by mishaone** [comment]
It seems abrupt to me because it interrupts the intended workflow. If the OSIO workflow to create a space, plan the work, then create/import a project, then it's odd UX design that the end of the create space wizard immediately launches into the create/import project wizard. 

The bug part is just because as I was following the instructions, the sudden planning didn't flow well. I was left with a create/import project screen with no instructions on how to get to the instructions required for the planning part. If this needs to remain here as the intended workflow, we should change the end of the create a space module and the beginning of the create project module to flow smoothly into the planner instructions.

The "If you closed the wizard earlier" part you mentioned is a bit vague (and was added in case people were confused about how to find the wizard if they arrived at that page from Google. I'd update the instructions to provide definite instructions about closing the wizard, going to planner, then starting the project wizard afresh. 

Thoughts? I'm happy to hold off on action but want to make sure we settle on a conclusion beforehand so that it can just be a matter of implementing whatever was decided later when appropriate.

**Comment by Preeticp** [comment]
> I'd update the instructions to provide definite instructions about closing the wizard, going to planner, then starting the project wizard afresh.

Agree on this, we need to do this.

On the intended workflow, I will discuss this with the devs and get back. I feel we would have users who might be interested only in Planning and tracking and those who might want to straight away get to implementation and execution. 
Like I said in the GSG context it made sense to have the Planning module at the start as it wove other things like analyzing, reducing resource consumption, testing, modifying code etc into a narrative while showcasing the feature.
Happy to modify the flow if needed.

**Comment by mishaone** [comment]
Yes, let's discuss this in person, it will be easier. I just want to make sure we have a smooth workflow for new users so that it doesn't leave them wondering what to do next at any point. :)

**Comment by rkratky** [comment]
Before I respond, two points:

1) We shouldn't get too hung up any guide's 'flow' -- even in the case of the GSG, which started out as a pretty little bedtime narrative. Let's always assume that users jump around in the doc, don't start from the beginning, and generally ignore all our attempts at guiding them from A to B because they want to read only the absolute minimum to get them going.

2) Likewise, we shouldn't think users follow any specific workflow or order of doing things in the app itself. They probably click around, try this and that, create a space, then adjust settings, then forget about OSIO for a week, then immediately try to open a Che instance, etc. The docs should try to be ready for this, especially wrt the fact that users only open docs when they get stuck -- not before they start doing stuff.

............

When looking at the GSG only, I don't find the flow interrupted. We should do a better job of linking modules together (in this case, "creating a space" should link to the module that describes it), but overall, I think it's OK. That said, I don't recall what it looks like in the app (and I haven't checked), so it's possible the guide is at odds with what the users see on the screen when they follow the "Creating a new space" module.

What's not OK is the module immediately after this, i.e. "5.3. About codebases" -- that seems totally out of place. I'm not disputing the importance of explaining the concept, but the concept module should be a part of some story, not just sitting in between procedure modules. IOW, we should first introduce the objective that justifies the inclusion of the concept module. Without that, we tell the user to create a space, do some planning, and then expect them to read about codebases without giving them a reason to.

**Comment by mishaone** [comment]
The conclusion after our discussion in the OSIO meeting was that we will modify the end/start text in the surrounding modules to transition more smoothly into the planner part. This will be done later, since there will be some changes coming up regarding the planner and using board view in particular in the near future.

**Comment by mishaone** [comment]
Are you happy to have this assigned to you, @Preeticp? I want to ensure every task has someone looking after it, even if nobody is working on it for the current sprint.

**Comment by Preeticp** [comment]
Closed via #408 and #411
