### ISSUE TITLE
Get rid of e2e directory

### ISSUE THREAD

**Issue by rkratky** [fabric8io/fabric8-online-docs#83]
The `e2e` directory under `modules` was only introduced because we thought the e2e doc will be phased out. That's not the case, so we want all our modules to live in the same directory.

@mishaone, @Preeticp, take note -- this will be another big restructuring. However, it will be very straightforward. We will just move all modules from `modules/e2e/` to  `modules/`.

**Comment by mishaone** [comment]
I'd recommend discussing this before making the decision. To me, the modules for the e2e are clunkier and catering more to what Todd wants rather than appropriately modular (reusable in various places because they are non-specific enough). I also anticipate making many more changes to these modules based on Todd's feedback for his preferred style of Getting Started doc so I don't think we would reuse much of these in, for example, the UG or other assemblies.

I do want to do a review and update the module file names at the end of my update since I did think these would be temporary and so we don't have names that correspond to the titles for many modules. However, having these in the same directory as our cleaner modules for the UG would create a lot of confusion (overlapping but somewhat different content, etc.).

**Comment by rkratky** [comment]
> To me, the modules for the e2e are clunkier and catering more to what Todd wants rather than appropriately modular (reusable in various places because they are non-specific enough).

True, but that's fixable. Having them in the 'reusable' space with the other modules would IMO help with this.

> I also anticipate making many more changes to these modules based on Todd's feedback for his preferred style of Getting Started doc so I don't think we would reuse much of these in, for example, the UG or other assemblies.

Reuse is not the only motivation, but it would be good to have the opportunity.

> I do want to do a review and update the module file names at the end of my update since I did think these would be temporary and so we don't have names that correspond to the titles for many modules.

I was actually planning to do that, so it's good to hear it's on your radar. Please, file an issue for it, so that it's tracked.

> However, having these in the same directory as our cleaner modules for the UG would create a lot of confusion (overlapping but somewhat different content, etc.).

Possibly, but it would also force us to fix the problems.

Overall, I believe we need to move in this direction. The e2e doc isn't going anywhere in the near future, so we should start treating it as a regular part of our docs set.

I was actually motivated to start thinking about this by the fact that for issue #61, I want to reuse the module from e2e in the UG.

**Comment by rkratky** [comment]
> Reusing and cross-linking would be great but we will have to take up fixing 'overlapping but somewhat different content' as top priority. I really see no point in having 2 versions of Analytics and Work items modules. We will have to streamline or reconcile them.

Agree.

>  I agree this will force us to fix the problems.

So you're good with the change?

**Comment by mishaone** [comment]
OK, created https://github.com/fabric8io/fabric8-online-docs/issues/90 to track the fixing of file names. Holding off because I'm moving around and changing a lot of content and titles at the moment. I'm OK to have the two sets of modules stored at the same place generally.

**Comment by Preeticp** [comment]
> So you're good with the change?
Absolutely, +1. I have a feeling this would help us come up with apt assemblies when required. We seem to be moving in the right direction, not only on this, but also in streamlining the Styles, Headings etc. as per one standard.
